name: UniSchedule
description: UniSchedule - application to view an university schedule.
publish_to: 'none'
version: 0.2.2+20

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_linkify: ^6.0.0
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  http: ^1.2.0
  meta: ^1.10.0
  package_info_plus: ^7.0.0
  path_provider: ^2.1.2 # wanted by inappwebview
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  flutter_inappwebview: ^6.0.0
  week_of_year: ^2.2.0
  share_plus: ^8.0.2
  permission_handler: ^11.3.0
  flutter_colorpicker: ^1.0.3
  intl: ^0.19.0
  flutter_downloader: ^1.11.6
  provider: ^6.1.2
  flutter_markdown: ^0.7.1

dev_dependencies:
  build_runner:
  riverpod_generator:
  riverpod_lint: # ^2.1.1

flutter:
  uses-material-design: true
  assets:
  - assets/images/icon.png

  - assets/copying.md

  - assets/dino-runner/index.html

  - assets/images/services/GPLv3Logo.svg.vec

  - assets/images/services/light-cmc-logo.svg.vec
  - assets/images/services/cmc-logo.svg.vec
  - assets/images/services/trex.svg.vec
  - assets/images/services/courses.svg.vec
  - assets/images/services/feedback.svg.vec
  - assets/images/services/info.svg.vec
  - assets/images/services/join.svg.vec
  - assets/images/services/map.svg.vec
  - assets/images/services/money.svg.vec
  - assets/images/services/report.svg.vec
  - assets/images/services/study_office.svg.vec
  - assets/images/services/write_us.svg.vec
  - assets/images/services/yandex_disk.svg.vec

  - assets/plans/MSU/PHYS/floor-plan-1.svg.vec
  - assets/plans/MSU/PHYS/floor-plan1.svg.vec
  - assets/plans/MSU/PHYS/floor-plan2.svg.vec
  - assets/plans/MSU/PHYS/floor-plan3.svg.vec
  - assets/plans/MSU/PHYS/floor-plan4.svg.vec
  - assets/plans/MSU/PHYS/floor-plan5.svg.vec
  - assets/plans/MSU/SAB/floor-plan1.svg.vec
  - assets/plans/MSU/SAB/floor-plan2.svg.vec
  - assets/plans/MSU/SAB/floor-plan2.svg.vec
  - assets/plans/MSU/BIO/floor-plan1.svg.vec
