name: UniSchedule
description: UniSchedule - application to view an university schedule.
publish_to: 'none'
version: 0.1.4+8

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_linkify: ^6.0.0
  flutter_riverpod: ^2.4.9
  http: ^1.2.0
  meta: ^1.10.0
  package_info_plus: ^5.0.1
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  week_of_year: ^2.2.0

dev_dependencies:
  build_runner:
  riverpod_generator:
  riverpod_lint: # ^2.1.1

flutter:
  uses-material-design: true
