name: UniSchedule
description: UniSchedule - application to view an university schedule.
publish_to: 'none'
version: 0.1.11+16

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_linkify: ^6.0.0
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  http: ^1.2.0
  meta: ^1.10.0
  package_info_plus: ^5.0.1
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  week_of_year: ^2.2.0

dev_dependencies:
  build_runner:
  riverpod_generator:
  riverpod_lint: # ^2.1.1

flutter:
  uses-material-design: true
  assets:
  - assets/images/icon.png
  - assets/plans/MSU/PHYS/floor-plan-1.svg.vec
  - assets/plans/MSU/PHYS/floor-plan1.svg.vec
  - assets/plans/MSU/PHYS/floor-plan2.svg.vec
  - assets/plans/MSU/PHYS/floor-plan3.svg.vec
  - assets/plans/MSU/PHYS/floor-plan4.svg.vec
  - assets/plans/MSU/PHYS/floor-plan5.svg.vec
  - assets/plans/MSU/SAB/floor-plan1.svg.vec
  - assets/plans/MSU/SAB/floor-plan2.svg.vec
  - assets/plans/MSU/SAB/floor-plan2.svg.vec
  - assets/plans/MSU/BIO/floor-plan1.svg.vec
